spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/project/h2/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
    show-sql: false

logging.level:
  org.hibernate.SQL: off
#  org.hibernate.type: trace